# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/10_gstreamer.valve.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/api/10_gstreamer.valve.ipynb 6
from UAV.imports import *   # TODO why is this relative import on nbdev_export?
from fastcore.utils import *
import gi
import numpy as np
import threading
gi.require_version('Gst', '1.0')
from gi.repository import Gst
import subprocess
import platform

import paho.mqtt.client as mqtt_client

import time

from pathlib import Path
import logging
import UAV.params as params
from UAV.gstreamer.valve import *
