# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/20_mavlink.cam_client.ipynb.

# %% auto 0
__all__ = ['logger']

# %% ../../nbs/api/20_mavlink.cam_client.ipynb 7
from ..imports import *   # TODO why is this relative import on nbdev_export?
import cv2

import numpy as np
from imutils import resize

import threading
import time
from pymavlink import mavutil
import threading
import logging
import UAV.params as params

# gi.require_version('Gst', '1.0')

# %% ../../nbs/api/20_mavlink.cam_client.ipynb 8
logging.basicConfig(format='%(asctime)-8s,%(msecs)-3d %(levelname)5s [%(filename)10s:%(lineno)3d] %(message)s',
                    datefmt='%H:%M:%S',
                    level=params.LOGGING_LEVEL)  # Todo add this to params
logger = logging.getLogger(params.LOGGING_NAME)
