# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/16_airsim.commands.ipynb.

# %% auto 0
__all__ = ['logger']

# %% ../../nbs/api/16_airsim.commands.ipynb 5
from fastcore.utils import *

from UAV.airsim.client import AirSimClient
import UAV.airsim_python_client as airsim
import UAV.params as params
import time
from UAV.utils.sim_linux import RunSim, is_process_running, find_and_terminate_process
import logging
from UAV.airsim.commands import *

# %% ../../nbs/api/16_airsim.commands.ipynb 6
logging.basicConfig(format='%(asctime)-8s,%(msecs)-3d %(levelname)5s [name] [%(filename)10s:%(lineno)3d] %(message)s',
                    datefmt='%H:%M:%S',
                    level=params.LOGGING_LEVEL) 
logger = logging.getLogger(params.LOGGING_NAME)
