# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/22_mavlink.viewsheen_gimbal.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/api/22_mavlink.viewsheen_gimbal.ipynb 7
import time, os, sys

from UAV.logging import logging
from UAV.mavlink.mavcom import MAVCom
from UAV.mavlink.component import Component, mavutil
# from viewsheen_sdk.gimbal_cntrl import pan_tilt, snapshot,  zoom, VS_IP_ADDRESS, VS_PORT, KeyReleaseThread
from UAV.camera_sdks.viewsheen.gimbal_cntrl import pan_tilt, snapshot,  zoom, VS_IP_ADDRESS, VS_PORT, KeyReleaseThread

from UAV.mavlink.vs_gimbal import *

# from UAV.imports import *   # TODO why is this relative import on nbdev_export?

