# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/17_camera.control.ipynb.

# %% auto 0
__all__ = ['gstreamerCamera', 'airsimCamera', 'videoCamera']

# %% ../../nbs/api/17_camera.control.ipynb 8
def gstreamerCamera(camera_name):
    """
    Set up streaming pipeline for Gstreamer camera.
    
    """
    return True

# %% ../../nbs/api/17_camera.control.ipynb 9
def airsimCamera(camera_name):
    """
    Set up streaming pipeline for Airsim camera
    """
    return True


# %% ../../nbs/api/17_camera.control.ipynb 10
def videoCamera(camera_name):
    """
    Set up streaming pipeline for Video camera
    """
    return True


# %% ../../nbs/api/17_camera.control.ipynb 11
def videoCamera(camera_name):
    """
    Set up streaming pipeline for Video camera
    """
    return True

