# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/UAV',
                'doc_host': 'https://johnnewto.github.io',
                'git_url': 'https://github.com/johnnewto/UAV',
                'lib_path': 'UAV'},
  'syms': {'UAV.core': {'UAV.core.foo': ('core.html#foo', 'UAV/core.py')}}}
