# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/15_airsim.ipynb.

# %% auto 0
__all__ = ['logger']

# %% ../nbs/api/15_airsim.ipynb 7
from fastcore.utils import *
import cv2
import numpy as np
from imutils import resize
import threading

import platform
import UAV.airsim

import paho.mqtt.client as mqtt_client
from .utils.display import *
import time
from pathlib import Path
import logging
# import .nbs.Gstreamer.gst_parameters as params

# %% ../nbs/api/15_airsim.ipynb 8
logging.basicConfig(format='%(asctime)-8s,%(msecs)-3d %(levelname)5s [%(filename)10s:%(lineno)3d] %(message)s',
                    datefmt='%H:%M:%S',
                    level=logging.INFO)  # Todo add this to params
logger = logging.getLogger(__name__)

# %% ../nbs/api/15_airsim.ipynb 9
# gi.require_version('Gst', '1.0')
