# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/02_maker.ipynb.

# %% ../nbs/api/02_maker.ipynb 1
from __future__ import annotations

# %% auto 0
__all__ = []

# %% ../nbs/api/02_maker.ipynb 3
from nbdev.config import *
from nbdev.imports import *

from fastcore.script import *
from fastcore.basics import *
from fastcore.imports import *
from execnb.nbio import *

import ast,contextlib

from collections import defaultdict
from pprint import pformat
from textwrap import TextWrapper
